import type { Article } from "./types";

export const fallbackArticles: Article[] = [
  { id: "open-source-ai-labs", title: "The open-source AI labs changing how the world builds", description: "A new generation of research teams is making powerful tools available to everyone, reshaping the pace of innovation.", content: "Across research labs and small studios, open models are becoming the new public infrastructure for experimentation. The shift is giving more people access to capable tools while raising new questions about trust, attribution, and governance.", url: "https://example.com/open-source-ai-labs", imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=85", publishedAt: "2026-09-08T08:30:00.000Z", sourceName: "Claude Bit News", category: "technology" },
  { id: "quiet-power-grid", title: "The quiet technology making the power grid more resilient", description: "Utilities are turning to a familiar class of software to balance demand and prepare for a more volatile energy future.", content: "The modern grid is becoming less about a few giant generators and more about coordinating millions of small decisions. Better forecasting and responsive demand are already changing how cities handle peaks.", url: "https://example.com/quiet-power-grid", imageUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1200&q=85", publishedAt: "2026-09-08T07:45:00.000Z", sourceName: "World Desk", category: "science" },
  { id: "markets-morning-brief", title: "Markets open cautiously as investors weigh a week of big data", description: "Traders are watching fresh labor and inflation signals as central banks enter a critical stretch of the year.", url: "https://example.com/markets-morning-brief", imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=900&q=85", publishedAt: "2026-09-08T06:50:00.000Z", sourceName: "Market Journal", category: "business" },
  { id: "city-sporting-week", title: "A city-wide sporting week brings elite competition outdoors", description: "New formats and public spaces are putting spectators closer to the action than ever.", url: "https://example.com/city-sporting-week", imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85", publishedAt: "2026-09-08T05:20:00.000Z", sourceName: "The Daily Play", category: "sports" },
  { id: "small-screen-big-ideas", title: "Why the most interesting stories are moving to the small screen", description: "Independent filmmakers are finding new audiences with intimate, ambitious work made outside the traditional studio system.", url: "https://example.com/small-screen-big-ideas", imageUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=85", publishedAt: "2026-09-07T22:10:00.000Z", sourceName: "Culture Edit", category: "entertainment" },
  { id: "sleep-science-update", title: "Sleep science gets practical", description: "Researchers are translating years of lab work into calmer, more useful advice for everyday routines.", url: "https://example.com/sleep-science-update", imageUrl: "https://images.unsplash.com/photo-1511295742362-92c96b1cf484?auto=format&fit=crop&w=900&q=85", publishedAt: "2026-09-07T20:15:00.000Z", sourceName: "Good Health", category: "health" },
];